v <- c(92,95,98,89)
g_range <- range(0, v)
plot(v, type="o", col="brown", ylim=g_range, axes=FALSE, ann=FALSE)
axis(1, at=1:4, lab=c("CNN","VGG-16","Inception V3","MobileNet"))
axis(2, las=1, at=20*0:g_range[2])
box()
title(xlab="Models", col.lab=rgb(0,0.5,0))
title(ylab="Accuracy", col.lab=rgb(0,0.5,0))
title(main="Simulation Results")
     # , col.main="red", font.main=4)
