v <- c(92, 95, 94)
g_range <- range(0, v)
plot(v, type="o", col="green", ylim=g_range, axes=FALSE, ann=FALSE)
#plot(v, type="o", col="green", ylim=g_range, axes=FALSE, ann=FALSE)
#plot(v, type="o", col="blue", ylim=g_range, axes=FALSE, ann=FALSE)
axis(1, at=1:3, lab=c("Bacterial leaf blight","Brown spot","leaf smut"))
axis(2, las=1, at=20*0:g_range[2])
box()
title(xlab="Paddy crop stresses", col.lab=rgb(0,0.5,0))
title(ylab="Accuracy", col.lab=rgb(0,0.5,0))
title(main="VGG-16 Results")